# Generated by Django 4.2.5 on 2023-09-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_transactions', to='couriers.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('ADEDUCTION_FROM_INCOME', 'Deduction from income'), ('INCREASE_INCOME', 'Increase income'), ('INCOME', 'Income')], max_length=23)),
                ('tx_daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='couriers.transactiondaily')),
            ],
        ),
    ]
