# Generated by Django 4.2.5 on 2023-09-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
